config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root :to => "orders#index"


  resources :orders
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:Name, :Tel, :Dish, :Price, :Number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lunch</title>
    <%= csrf_meta_tags %>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
   <%= link_to '點餐囉123', root_path,class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">菜單 <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active"><a class="nav-link" href="#">點餐</a></li>
    </ul>    
        
    <ul class="nav justify-content-end">
        <% if current_user %>
        <li> <%= link_to '登出', destroy_user_session_path, :method => :delete ,class:  "nav-link" %></li>
        <li> <%= link_to '修改密碼', edit_registration_path(:user)  ,class: "nav-link" %></li>
        <% else %>
        <li> <%= link_to '註冊', new_registration_path(:user) ,class: "nav-link" %></li>
        <li> <%= link_to '登入', new_session_path(:user) ,class: "nav-link" %></li>
        <% end %>
    </ul> 


        
  </div>
</nav>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>




  <div class="container">
  <%= yield %>
  </div>
    
  </body>
</html>

app/views/orders/_form.html.erb
<%= form_with(model: order, local: true) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :姓名 %>
    <%= form.text_field :Name, id: :order_Name %>
  </div>

  <div class="field">
    <%= form.label :電話 %>
    <%= form.text_field :Tel, id: :order_Tel %>
  </div>

  <div class="field">
    <%= form.label :餐點 %>
    <%= form.text_field :Dish, id: :order_Dish %>
  </div>

  <div class="field">
    <%= form.label :價格 %>
    <%= form.number_field :Price, id: :order_Price %>
  </div>

  <div class="field">
    <%= form.label :數量 %>
    <%= form.number_field :Number, id: :order_Number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>修改餐點</h1>

<%= render 'form', order: @order %>

<%= link_to '顯示', @order %> |
<%= link_to '返回', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>點餐囉</h1>

<table class="table">
  <thead>
    <tr>
      <th>姓名</th>
      <th>電話</th>
      <th>餐點</th>
      <th>價格</th>
      <th>數量</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.Name %></td>
        <td><%= order.Tel %></td>
        <td><%= order.Dish %></td>
        <td><%= order.Price %></td>
        <td><%= order.Number %></td>
        <%# <%= link_to '點餐囉', root_path,class: "navbar-brand" %> 
        <td><%= link_to '顯示' , order, class:  "btn btn-primary" %></td>
        <td><%= link_to '修改' , edit_order_path(order),class:  "btn btn-primary" %></td>
        <td><%= link_to '刪除' , order, method: :delete, data: { confirm: '你確定嗎？' } ,class:  "btn btn-primary" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '點餐', new_order_path %>

app/views/orders/new.html.erb
<h1>點餐囉</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>姓名:</strong>
  <%= @order.Name %>
</p>

<p>
  <strong>電話:</strong>
  <%= @order.Tel %>
</p>

<p>
  <strong>餐點:</strong>
  <%= @order.Dish %>
</p>

<p>
  <strong>價格:</strong>
  <%= @order.Price %>
</p>

<p>
  <strong>數量:</strong>
  <%= @order.Number %>
</p>

<%= link_to '修改', edit_order_path(@order) %> |
<%= link_to '返回', orders_path %>